# Site settings
title: CDM

# Contact information
street_address: 27 rue de la Laye
city: Laduz-Valravillon
state: Yonne
zip_code: 89110
country: France
phone: (33) 633-695-568
email: contact@c-dm.com

# Social settings
github_url: https://github.com/moodule
gitlab_url:
linkedin_url: https://fr.linkedin.com/in/denis-mougeolle-05843858
twitter_url:

# Collections
collections:
  achievements:
    output: false
  yang:
    output: true
    subtitle: Supporting Industries from Decision to Operations
    description:
  yin:
    output: true
    subtitle: Outgrowing Incidents and Risks
    description: When it comes down to it, I assess the primary causes of incidents and make sure you grow from it.

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Publication settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://moodule.github.io/cdm" # the base hostname & protocol for your site, e.g. http://example.com
permalink: pretty
author: apehex

# Exclude from processing.
