# Site settings
title: CDM
subtitle: Making companies more resilient
email: contact@c-dm.com
description: >- # this means to ignore newlines until "baseurl:"
  I make companies more resilient to industrial risks.
  And when it comes down to it, I assess the primary causes of incidents
  and make sure your companies grows from it.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
author: apehex
street_address: 27 rue de la Laye 
city: Laduz-Valravillon
state: Yonne
zip_code: 89110
country: France
phone: (33) 633-695-568

# Social settings
twitter_username:
github_username: moodule
500px_url:
facebook_url:
github_url: https://github.com/moodule
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url: https://fr.linkedin.com/in/denis-mougeolle-05843858
pinterest_url:
slack_url:
twitter_url:

# Collections
collections:
  missions:
    output: false

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Publication settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
author: apehex

# Exclude from processing.
