# Site settings
title: CDM

# Contact information
street_address: 27 rue de la Laye
city: Laduz-Valravillon
state: Yonne
zip_code: 89110
country: France
phone: (33) 633-695-568
email: contact@c-dm.com

# Social settings
github_url: https://github.com/moodule
gitlab_url:
linkedin_url: https://fr.linkedin.com/in/denis-mougeolle-05843858
twitter_url:

# Collections
collections:
  achievements:
    output: false
  redirects:
    output: true
  yang:
    output: true
  yin:
    output: true

# Default settings
defaults:
  -
    scope:
      path: ""
    values:
      menu: "default"
      layout: "page"
  -
    scope:
      type: "redirects"
    values:
      layout: "redirect"
      lang: "x-default"
      permalink: /:path/
  -
    scope:
      path: "en"
    values:
      lang: "en"
  -
    scope:
      path: "en/yang"
    values:
      menu: "yang"
      title: "CDM"
      subtitle: "Supporting Companies from Decision to Operations"
  -
    scope:
      path: "en/yin"
    values:
      menu: "yin"
      title: "CDM"
      subtitle: "Outgrowing Incidents and Litigation"
      description: When it comes down to it, I assess the primary causes of incidents and make sure you grow from it.
  -
    scope:
      path: "fr"
    values:
      lang: "fr"
  -
    scope:
      path: "fr/yang"
    values:
      menu: "yang"
      title: "CDM"
      subtitle: "Accompagner de la Décision à l'Exploitation"
  -
    scope:
      path: "fr/yin"
    values:
      menu: "yin"
      title: "CDM"
      subtitle: "Dépasser les Incidents"

# Build settings
permalink: pretty
markdown: kramdown
theme: jekyll-theme-consulting
plugins:
  - jekyll-feed

# Publication settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://moodule.github.io/cdm" # the base hostname & protocol for your site, e.g. http://example.com
author: apehex

# Exclude from processing.
